version: '3'
services:
  app1:
    image: testdocker
    hostname: JustFors1
    ports:
      - 7000:7000
  app2:
    image: testdocker
    hostname: JustFors2
    ports:
      - 7001:7000
  app3:
    image: testdocker
    hostname: JustFors3
    ports:
      - 7002:7000
  app4:
    image: testdocker
    hostname: JustFors4
    ports:
      - 7003:7000
  app5:
    image: testdocker
    hostname: JustFors5
    ports:
      - 7004:7000
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - C:\Users\MC\IdeaProjects\docker\default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app1
      - app2
      - app3
      - app4
      - app5
    ports:
      - 8989:8989